# RUTA: src/components/train_lstm_launcher/component.yaml
# Component v2 de KFP: lanza el Custom Job anterior y expone la ruta resultante.

apiVersion: kfp.google.com/v2
kind: component
metadata:
  name: launch-vertex-ai-lstm-training-job
  annotations:
    author: "Manuel Rincón"
spec:
  inputs:
    parameters:
      - name: project_id
        parameterType: STRING
      - name: region
        parameterType: STRING
      - name: pair
        parameterType: STRING
      - name: timeframe
        parameterType: STRING
      - name: params_path
        parameterType: STRING
      - name: features_gcs_path
        parameterType: STRING
      - name: output_gcs_base_dir
        parameterType: STRING
      - name: vertex_training_image_uri
        parameterType: STRING
      - name: vertex_machine_type
        parameterType: STRING
      - name: vertex_accelerator_type
        parameterType: STRING
      - name: vertex_accelerator_count
        parameterType: NUMBER_INTEGER
      - name: vertex_service_account
        parameterType: STRING

  outputs:
    parameters:
      - name: trained_lstm_dir_path      # ← NUEVA salida que esperará la pipeline
        parameterType: STRING

  implementation:
    container:
      image: europe-west1-docker.pkg.dev/trading-ai-460823/containers/train-lstm-launcher:latest
      command: ["python", "-m", "src.components.train_lstm_launcher.task"]
      args:
        - --project-id
        - {inputValue: project_id}
        - --region
        - {inputValue: region}
        - --pair
        - {inputValue: pair}
        - --timeframe
        - {inputValue: timeframe}
        - --params-path
        - {inputValue: params_path}
        - --features-gcs-path
        - {inputValue: features_gcs_path}
        - --output-gcs-base-dir
        - {inputValue: output_gcs_base_dir}
        - --vertex-training-image-uri
        - {inputValue: vertex_training_image_uri}
        - --vertex-machine-type
        - {inputValue: vertex_machine_type}
        - --vertex-accelerator-type
        - {inputValue: vertex_accelerator_type}
        - --vertex-accelerator-count
        - {inputValue: vertex_accelerator_count}
        - --vertex-service-account
        - {inputValue: vertex_service_account}
        # ← Pasamos el archivo-salida que KFP creará
        - --trained-lstm-dir-path-output
        - {outputPath: trained_lstm_dir_path}
