apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: log-analyzer-service
  namespace: trading
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      containers:
      - image: gcr.io/trading-ai-460823/log-analyzer:latest
        ports:
        - containerPort: 8080
        env:
        - name: GCP_PROJECT_ID
          value: "trading-ai-460823"
        - name: GCP_REGION
          value: "europe-west1"
        - name: LOG_VERBOSE
          value: "true"
        - name: LOG_CONSOLE_OUTPUT
          value: "true"
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5 